
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mefgswdpeellvaggvttc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZmdzd2RwZWVsbHZhZ2d2dHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDQ1NTAsImV4cCI6MjA2MTMyMDU1MH0.9-PrOlsvyrYr8ZUq5C72B_W9L74stkpyqwBkc5xsq8Q";

// Instrumentação do fetch customizada para debug
const instrumentedFetch = (url: RequestInfo | URL, init?: RequestInit) => {
  const fetchId = `${Date.now()}-${Math.random().toString(36).substr(2, 6)}`;
  console.log(`[instrumentedFetch] → [${fetchId}]`, {
    url: url.toString(),
    method: init?.method || 'GET',
    headers: init?.headers,
    signal: init?.signal ? 'AbortSignal present' : 'no signal'
  });
  
  const start = performance.now();
  
  return Promise.race([
    fetch(url, init),
    new Promise((_, reject) => 
      setTimeout(() => reject(new Error(`[${fetchId}] Tempo limite de conexão excedido após 300s`)), 300000) // Aumentado para 300s
    )
  ]).then((response: Response) => {
    const duration = (performance.now() - start).toFixed(2);
    console.log(`[instrumentedFetch] ← [${fetchId}] ${response.status} em ${duration}ms`, {
      ok: response.ok,
      statusText: response.statusText,
      url: response.url
    });
    return response;
  }).catch((error) => {
    const duration = (performance.now() - start).toFixed(2);
    console.error(`[instrumentedFetch] ✗ [${fetchId}] erro após ${duration}ms:`, {
      error: error.message,
      name: error.name
    });
    throw error;
  }) as Promise<Response>;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit'
  },
  global: {
    fetch: instrumentedFetch
  }
});

// Debug adicional para Supabase
console.log('[Supabase Client] Inicializado com debug ativado');
