// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mefgswdpeellvaggvttc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZmdzd2RwZWVsbHZhZ2d2dHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDQ1NTAsImV4cCI6MjA2MTMyMDU1MH0.9-PrOlsvyrYr8ZUq5C72B_W9L74stkpyqwBkc5xsq8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);